// Copyright 2020 Harri @ OP Techlab.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: protocol.proto

package agency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type is enum type to identify the protocol, we aren't tight to Aries strings
type Protocol_Type int32

const (
	Protocol_CONNECT          Protocol_Type = 0
	Protocol_ISSUE            Protocol_Type = 1
	Protocol_PROPOSE_ISSUING  Protocol_Type = 2
	Protocol_REQUEST_PROOF    Protocol_Type = 3
	Protocol_PROPOSE_PROOFING Protocol_Type = 4
	Protocol_TRUST_PING       Protocol_Type = 5
	Protocol_BASIC_MESSAGE    Protocol_Type = 6
	Protocol_CONTINUE_ISSUING Protocol_Type = 7
	Protocol_CONTINUE_PROOF   Protocol_Type = 8
)

// Enum value maps for Protocol_Type.
var (
	Protocol_Type_name = map[int32]string{
		0: "CONNECT",
		1: "ISSUE",
		2: "PROPOSE_ISSUING",
		3: "REQUEST_PROOF",
		4: "PROPOSE_PROOFING",
		5: "TRUST_PING",
		6: "BASIC_MESSAGE",
		7: "CONTINUE_ISSUING",
		8: "CONTINUE_PROOF",
	}
	Protocol_Type_value = map[string]int32{
		"CONNECT":          0,
		"ISSUE":            1,
		"PROPOSE_ISSUING":  2,
		"REQUEST_PROOF":    3,
		"PROPOSE_PROOFING": 4,
		"TRUST_PING":       5,
		"BASIC_MESSAGE":    6,
		"CONTINUE_ISSUING": 7,
		"CONTINUE_PROOF":   8,
	}
)

func (x Protocol_Type) Enum() *Protocol_Type {
	p := new(Protocol_Type)
	*p = x
	return p
}

func (x Protocol_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[0].Descriptor()
}

func (Protocol_Type) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[0]
}

func (x Protocol_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol_Type.Descriptor instead.
func (Protocol_Type) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0, 0}
}

type ProtocolState_State int32

const (
	ProtocolState_OK          ProtocolState_State = 0 // Protocol is finalized successfully
	ProtocolState_ERR         ProtocolState_State = 1 // Protocol is finalized with error or other side NACK
	ProtocolState_WAIT_ACTION ProtocolState_State = 2 // Protocol is waiting user's action to continue
	ProtocolState_ACK         ProtocolState_State = 3 // User tells for the protocol to proceed
	ProtocolState_NACK        ProtocolState_State = 4 // User tells for the protocol not to proceed
)

// Enum value maps for ProtocolState_State.
var (
	ProtocolState_State_name = map[int32]string{
		0: "OK",
		1: "ERR",
		2: "WAIT_ACTION",
		3: "ACK",
		4: "NACK",
	}
	ProtocolState_State_value = map[string]int32{
		"OK":          0,
		"ERR":         1,
		"WAIT_ACTION": 2,
		"ACK":         3,
		"NACK":        4,
	}
)

func (x ProtocolState_State) Enum() *ProtocolState_State {
	p := new(ProtocolState_State)
	*p = x
	return p
}

func (x ProtocolState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[1].Descriptor()
}

func (ProtocolState_State) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[1]
}

func (x ProtocolState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolState_State.Descriptor instead.
func (ProtocolState_State) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2, 0}
}

//
//Protocol is the actual DIDComm/Aries protocol.
type Protocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeId       Protocol_Type `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3,enum=agency.Protocol_Type" json:"type_id,omitempty"` // Protocol type
	PrevThreadId string        `protobuf:"bytes,2,opt,name=prev_thread_id,json=prevThreadId,proto3" json:"prev_thread_id,omitempty"`        // Previous protocol ID if there was any
	ConnectionId string        `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`          // pairwise ID, this only empty when Type is CONNECT
	// Protocol type specific data: one of or no one
	//
	// Types that are assignable to StartMsg:
	//	*Protocol_InvitationJson
	//	*Protocol_CredDef
	//	*Protocol_ProofAttributesJson
	StartMsg isProtocol_StartMsg `protobuf_oneof:"StartMsg"`
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Protocol) GetTypeId() Protocol_Type {
	if x != nil {
		return x.TypeId
	}
	return Protocol_CONNECT
}

func (x *Protocol) GetPrevThreadId() string {
	if x != nil {
		return x.PrevThreadId
	}
	return ""
}

func (x *Protocol) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (m *Protocol) GetStartMsg() isProtocol_StartMsg {
	if m != nil {
		return m.StartMsg
	}
	return nil
}

func (x *Protocol) GetInvitationJson() string {
	if x, ok := x.GetStartMsg().(*Protocol_InvitationJson); ok {
		return x.InvitationJson
	}
	return ""
}

func (x *Protocol) GetCredDef() *Protocol_Issuing {
	if x, ok := x.GetStartMsg().(*Protocol_CredDef); ok {
		return x.CredDef
	}
	return nil
}

func (x *Protocol) GetProofAttributesJson() string {
	if x, ok := x.GetStartMsg().(*Protocol_ProofAttributesJson); ok {
		return x.ProofAttributesJson
	}
	return ""
}

type isProtocol_StartMsg interface {
	isProtocol_StartMsg()
}

type Protocol_InvitationJson struct {
	InvitationJson string `protobuf:"bytes,4,opt,name=invitation_json,json=invitationJson,proto3,oneof"` // Invitation JSON string, only for CONNECT
}

type Protocol_CredDef struct {
	CredDef *Protocol_Issuing `protobuf:"bytes,5,opt,name=cred_def,json=credDef,proto3,oneof"` // Only for Issuing protocol
}

type Protocol_ProofAttributesJson struct {
	ProofAttributesJson string `protobuf:"bytes,6,opt,name=proof_attributes_json,json=proofAttributesJson,proto3,oneof"` // Only for Proof protocol
}

func (*Protocol_InvitationJson) isProtocol_StartMsg() {}

func (*Protocol_CredDef) isProtocol_StartMsg() {}

func (*Protocol_ProofAttributesJson) isProtocol_StartMsg() {}

//
//Protocol ID is a primary minimal identification of the _current_ protocol
//conversation. Protocol is an elementary concept in SSI. With the protocols we
//build the trust over the state of the connection (aka pairwise). That's why the
//connection ID is always the most important thing and we should drive towards
//reuse of the previous connection when ever it's possible. Still, we operate with
//protocols.
type ProtocolID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeId Protocol_Type `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3,enum=agency.Protocol_Type" json:"type_id,omitempty"` // protocol type
	Id     string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                  // UUID of the current protocol
}

func (x *ProtocolID) Reset() {
	*x = ProtocolID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtocolID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolID) ProtoMessage() {}

func (x *ProtocolID) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolID.ProtoReflect.Descriptor instead.
func (*ProtocolID) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolID) GetTypeId() Protocol_Type {
	if x != nil {
		return x.TypeId
	}
	return Protocol_CONNECT
}

func (x *ProtocolID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ProtocolState is lightest and simplest way to tell outside what is going on
// during a protocol run.
type ProtocolState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolId *ProtocolID         `protobuf:"bytes,1,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	State      ProtocolState_State `protobuf:"varint,2,opt,name=state,proto3,enum=agency.ProtocolState_State" json:"state,omitempty"` // See the State enum, tells whats going on
	Info       string              `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`                                    // Extra information, mostly used for debugging
}

func (x *ProtocolState) Reset() {
	*x = ProtocolState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtocolState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolState) ProtoMessage() {}

func (x *ProtocolState) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolState.ProtoReflect.Descriptor instead.
func (*ProtocolState) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ProtocolState) GetProtocolId() *ProtocolID {
	if x != nil {
		return x.ProtocolId
	}
	return nil
}

func (x *ProtocolState) GetState() ProtocolState_State {
	if x != nil {
		return x.State
	}
	return ProtocolState_OK
}

func (x *ProtocolState) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// ProtocolStatus is message to include whole status of the protocol. This is
// UNDER CONSTRUCTION, TODO
type ProtocolStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State     *ProtocolState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Message   string         `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Timestamp uint64         `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ProtocolStatus) Reset() {
	*x = ProtocolStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtocolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolStatus) ProtoMessage() {}

func (x *ProtocolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolStatus.ProtoReflect.Descriptor instead.
func (*ProtocolStatus) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolStatus) GetState() *ProtocolState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ProtocolStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProtocolStatus) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Issuing attributes
type Protocol_Issuing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredDefId      string `protobuf:"bytes,1,opt,name=cred_def_id,json=credDefId,proto3" json:"cred_def_id,omitempty"`
	AttributesJson string `protobuf:"bytes,2,opt,name=attributes_json,json=attributesJson,proto3" json:"attributes_json,omitempty"`
}

func (x *Protocol_Issuing) Reset() {
	*x = Protocol_Issuing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Protocol_Issuing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol_Issuing) ProtoMessage() {}

func (x *Protocol_Issuing) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol_Issuing.ProtoReflect.Descriptor instead.
func (*Protocol_Issuing) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Protocol_Issuing) GetCredDefId() string {
	if x != nil {
		return x.CredDefId
	}
	return ""
}

func (x *Protocol_Issuing) GetAttributesJson() string {
	if x != nil {
		return x.AttributesJson
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

var file_protocol_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x22, 0xa9, 0x04, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x2e, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x74,
	0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x74, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x72, 0x65, 0x76, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x29, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x63,
	0x72, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x49, 0x73, 0x73, 0x75, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x07, 0x63, 0x72, 0x65, 0x64, 0x44,
	0x65, 0x66, 0x12, 0x34, 0x0a, 0x15, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x13, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x1a, 0x52, 0x0a, 0x07, 0x49, 0x73, 0x73, 0x75,
	0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x66, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x64, 0x44, 0x65,
	0x66, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0xa9, 0x01, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x53, 0x53, 0x55, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x50, 0x52, 0x4f, 0x50, 0x4f, 0x53, 0x45, 0x5f, 0x49, 0x53, 0x53, 0x55, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x50, 0x52,
	0x4f, 0x4f, 0x46, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x52, 0x4f, 0x50, 0x4f, 0x53, 0x45,
	0x5f, 0x50, 0x52, 0x4f, 0x4f, 0x46, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x54,
	0x52, 0x55, 0x53, 0x54, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x42,
	0x41, 0x53, 0x49, 0x43, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x06, 0x12, 0x14,
	0x0a, 0x10, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x49, 0x53, 0x53, 0x55, 0x49,
	0x4e, 0x47, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45,
	0x5f, 0x50, 0x52, 0x4f, 0x4f, 0x46, 0x10, 0x08, 0x42, 0x0a, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4d, 0x73, 0x67, 0x22, 0x4c, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x49, 0x44, 0x12, 0x2e, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0xc9, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x22, 0x3c, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x52, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x41,
	0x49, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x43, 0x4b, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41, 0x43, 0x4b, 0x10, 0x04, 0x22, 0x75,
	0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x32, 0x93, 0x02, 0x0a, 0x07, 0x44, 0x49, 0x44, 0x43, 0x6f, 0x6d,
	0x6d, 0x12, 0x32, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x10, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x15, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2f, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x1a, 0x12, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x49, 0x44, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x07, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x12, 0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x1a, 0x12, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x49, 0x44, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x07, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x12, 0x12, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6e, 0x64, 0x79, 0x2d,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x66, 0x69, 0x6e, 0x64, 0x79, 0x2d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData = file_protocol_proto_rawDesc
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_proto_rawDescData)
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protocol_proto_goTypes = []interface{}{
	(Protocol_Type)(0),       // 0: agency.Protocol.Type
	(ProtocolState_State)(0), // 1: agency.ProtocolState.State
	(*Protocol)(nil),         // 2: agency.Protocol
	(*ProtocolID)(nil),       // 3: agency.ProtocolID
	(*ProtocolState)(nil),    // 4: agency.ProtocolState
	(*ProtocolStatus)(nil),   // 5: agency.ProtocolStatus
	(*Protocol_Issuing)(nil), // 6: agency.Protocol.Issuing
}
var file_protocol_proto_depIdxs = []int32{
	0,  // 0: agency.Protocol.type_id:type_name -> agency.Protocol.Type
	6,  // 1: agency.Protocol.cred_def:type_name -> agency.Protocol.Issuing
	0,  // 2: agency.ProtocolID.type_id:type_name -> agency.Protocol.Type
	3,  // 3: agency.ProtocolState.protocol_id:type_name -> agency.ProtocolID
	1,  // 4: agency.ProtocolState.state:type_name -> agency.ProtocolState.State
	4,  // 5: agency.ProtocolStatus.state:type_name -> agency.ProtocolState
	2,  // 6: agency.DIDComm.Run:input_type -> agency.Protocol
	2,  // 7: agency.DIDComm.Start:input_type -> agency.Protocol
	3,  // 8: agency.DIDComm.Status:input_type -> agency.ProtocolID
	4,  // 9: agency.DIDComm.Unpause:input_type -> agency.ProtocolState
	3,  // 10: agency.DIDComm.Release:input_type -> agency.ProtocolID
	4,  // 11: agency.DIDComm.Run:output_type -> agency.ProtocolState
	3,  // 12: agency.DIDComm.Start:output_type -> agency.ProtocolID
	5,  // 13: agency.DIDComm.Status:output_type -> agency.ProtocolStatus
	3,  // 14: agency.DIDComm.Unpause:output_type -> agency.ProtocolID
	3,  // 15: agency.DIDComm.Release:output_type -> agency.ProtocolID
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Protocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtocolID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtocolState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtocolStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Protocol_Issuing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocol_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Protocol_InvitationJson)(nil),
		(*Protocol_CredDef)(nil),
		(*Protocol_ProofAttributesJson)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_rawDesc = nil
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
